PRAGMA foreign_keys = OFF;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS optimum_members;
DROP TABLE IF EXISTS suppliers;
DROP TABLE IF EXISTS product_details;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS medications;
DROP TABLE IF EXISTS patients;
DROP TABLE IF EXISTS prescriptions;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS order_details;
DROP TABLE IF EXISTS insurance;
DROP TABLE IF EXISTS filled_prescriptions;
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS product_sales;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS insurance_payments;
PRAGMA foreign_keys = ON;