"""empty message

Revision ID: f7c5484643d1
Revises: 
Create Date: 2024-11-18 20:19:29.331549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c5484643d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.CheckConstraint("email LIKE '%_@_%._%'"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_address', sa.String(length=255), nullable=False),
    sa.Column('suite_no', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=6), nullable=False),
    sa.Column('pharmacy_owner', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placed_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_on', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_details',
    sa.Column('upc_a', sa.String(length=15), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('details', sa.String(length=3000), nullable=True),
    sa.PrimaryKeyConstraint('upc_a')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('credit_owing', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_owing', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.CheckConstraint("email LIKE '%_@_%._%'"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_name')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=15), nullable=False),
    sa.Column('employee_password', sa.String(length=60), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('payroll_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_id')
    )
    op.create_table('optimum_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('optimum_points', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('spouse_id', sa.Integer(), nullable=True),
    sa.Column('parent_1_id', sa.Integer(), nullable=True),
    sa.Column('parent_2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_1_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_2_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spouse_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upc_a', sa.String(length=15), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('retail_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['upc_a'], ['product_details.upc_a'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance',
    sa.Column('policy_id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['patients.customer_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_table('inventory',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('on_backorder', sa.Integer(), nullable=False),
    sa.CheckConstraint('on_backorder IN (0, 1)', name='check_on_backorder'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'location_id', name='inventory_id')
    )
    op.create_table('medications',
    sa.Column('drug_indentification_number', sa.String(length=8), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('drug_indentification_number')
    )
    op.create_table('order_details',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_payments',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('insurance_policy_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['insurance_policy_id'], ['insurance.policy_id'], ondelete='SET CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id', 'insurance_policy_id')
    )
    op.create_table('payments',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('method_of_payment', sa.String(length=15), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.CheckConstraint("method_of_payment IN ('cash', 'debit', 'mastercard', 'visa', 'amex', 'insurance')", name='check_method_of_payment'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id', 'method_of_payment', name='payment_id')
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('drug_indentification_number', sa.String(length=8), nullable=True),
    sa.Column('practitioner_mnic', sa.String(length=14), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['patients.customer_id'], ondelete='SET CASCADE'),
    sa.ForeignKeyConstraint(['drug_indentification_number'], ['medications.drug_indentification_number'], ondelete='SET CASCADE'),
    sa.PrimaryKeyConstraint('id', 'customer_id')
    )
    op.create_table('product_sales',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id', 'product_id', name='sales_id')
    )
    op.create_table('filled_prescriptions',
    sa.Column('precription_id', sa.Integer(), nullable=False),
    sa.Column('fill_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['precription_id'], ['prescriptions.id'], ondelete='SET CASCADE'),
    sa.PrimaryKeyConstraint('precription_id', 'fill_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filled_prescriptions')
    op.drop_table('product_sales')
    op.drop_table('prescriptions')
    op.drop_table('payments')
    op.drop_table('insurance_payments')
    op.drop_table('transactions')
    op.drop_table('order_details')
    op.drop_table('medications')
    op.drop_table('inventory')
    op.drop_table('insurance')
    op.drop_table('products')
    op.drop_table('patients')
    op.drop_table('optimum_members')
    op.drop_table('employees')
    op.drop_table('suppliers')
    op.drop_table('product_details')
    op.drop_table('orders')
    op.drop_table('locations')
    op.drop_table('departments')
    op.drop_table('customers')
    # ### end Alembic commands ###
